### ISSUE TITLE
Failed run on the example code 

### ISSUE THREAD

**Issue by aaita92** [qiskit-community/qiskit_rng#10]
### Information

- **Qiskit RNG version**:  0.2.1
- **Python version**: 3.8.3
- **Operating system**: Mac OS 10.15.7

### What is the current behavior?
running the example code:

> from qiskit import IBMQ
> from qiskit_rng import Generator
> 
> IBMQ.load_account()
> rng_provider = IBMQ.get_provider(hub='ibm-q', group='open', project='main')
> backend = rng_provider.backends.ibmq_ourense
> 
> generator = Generator(backend=backend)
> 
> output = generator.sample(num_raw_bits=1024).block_until_ready()
> print(output.mermin_correlator)

 I get the exception: 

`IBMQManagedResultDataNotAvailable: 'Results cannot be combined since some of the jobs failed.'`

and checking on the *quantum experience* GUI in the Last Results panel I got the following exit status related to jobID generated by the execution.

![image](https://user-images.githubusercontent.com/31774156/102894015-c0610680-4462-11eb-830b-5f7e3c3345aa.png)

**Comment by jyu00** [comment]
@aaita92 Thanks for reporting this! It's due to the bug Qiskit/qiskit-terra/issues/5644 in qiskit-terra. 

Optimization level 2 was chosen because it gives the most optimal output for the circuits used in this RNG (level 3 works too but slower). Therefore it's probably better to allow users to pick an optimization level (default to 2) when creating the `Generator` instance, rather than changing the hard coded level to 1.
